"""change the State in the Enum

Revision ID: c269cbff36e7
Revises: cce04a6e76b0
Create Date: 2024-10-01 02:15:14.232959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c269cbff36e7'
down_revision: Union[str, None] = 'cce04a6e76b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('approval', 'complainer', 'admin', name='roletypes'),
               type_=sa.Enum('approver', 'complainer', 'admin', name='roletype'),
               existing_nullable=False,
               existing_server_default=sa.text("'complainer'::roletypes"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('approver', 'complainer', 'admin', name='roletype'),
               type_=postgresql.ENUM('approval', 'complainer', 'admin', name='roletypes'),
               existing_nullable=False,
               existing_server_default=sa.text("'complainer'::roletypes"))
    # ### end Alembic commands ###
